# Generated by Django 4.1.2 on 2022-10-31 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_choice_vote_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='question_id',
            new_name='question',
        ),
    ]
