# Generated by Django 4.1.2 on 2022-10-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_remove_question_pub_date_question_time_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='time_create',
            new_name='pub_date',
        ),
    ]
